# This script reads the JSON generated by gen.py and applies it

import json
import os
from pprint import pprint

OUTNAME = 'fs.generated.json'


def read_file():
    with open(OUTNAME, 'r') as file:
        return json.load(file)


def apply(fsmap):
    items = fsmap['org']

    for basedir, category in items:
        path_to_category = f'{basedir}/{category}'
        os.rmdir(path_to_category)


apply(fsmap=read_file())
