# This script reads the JSON generated by gen.py and applies it

import json
import os
import shutil
from pprint import pprint

OUTNAME = 'fs.generated.json'


def read_file():
    with open(OUTNAME, 'r') as file:
        return json.load(file)


def apply(fsmap):
    org = fsmap['org']

    for basedir, categories in org.items():
        for category, files in categories.items():
            path_to_category = f'{basedir}/{category}'

            if os.path.exists(path_to_category):
                os.rmdir(path_to_category)

            os.mkdir(path_to_category)

            # Move the files

            for file in files:
                base_path_to_file = f'{basedir}/{file}'
                moved_file_path = f'{path_to_category}/{file}'
                shutil.move(base_path_to_file, moved_file_path)


apply(fsmap=read_file())
